public enum Dispositivos{
    AIRE_ACONDICIONADO, ASPIRADORA, CAFETERA, CELULAR, COMPUTADORA, CONSOLA, DUCHA,
    EQUIPO_DE_SONIDO, FOCO, IMPRESORA, LAMPARA, LAPTOP, LAVADORA, LICUADORA, MICROONDAS, 
    OTROS, PLANCHA, REFIGERADORA, ROUTER, SECADORA, TELEVISION, TOSTADORA, VENTILADOR
}
